# Site settings
title: dolm.us
header-img: img/kadikoy.jpg
description: "A site not really about dolmus"
baseurl: ""
url: "http://dolm.us"
github_username:  behcet-li
timezone: America/New_York

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "vendor"]

gems: [jekyll-paginate, jekyll-feed]
# Serve settings
host: 0.0.0.0

# App specific
social:
  - title: github
    url: https://github.com/behcet-li
  - title: linkedin
    url: https://www.linkedin.com/pub/behcet-uyar/4b/457/661

# jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/img
    - _assets/js
    - _assets/scss
  jscompressor: uglifier
  css_compressor: ~
  autosize: false
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]