# Site settings
title: dolm.us
header-img: kadikoy.jpg
description: "A site not really about dolmus"
baseurl: ""
url: "http://dolm.us"
github_username:  behcet
timezone: America/New_York

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
exclude: [
  "node_modules",
  "Gruntfile.js",
  "package.json",
  "README.md",
  "Gemfile",
  "deploy.conf",
  "deploy.sh",
  "build.sh",
  "assets"
]

gems: [
  jekyll-assets,
  jekyll-paginate,
  jekyll-feed,
  bootstrap-sass,
  uglifier,
  jekyll/responsive_image
]

# Serve settings
host: 0.0.0.0

# App specific
social:
  - title: github
    url: https://github.com/behcet
  - title: linkedin
    url: https://www.linkedin.com/pub/behcet-uyar/4b/457/661

# jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/js
    - _assets/scss
  compress:
    js: true
    css: true
  digest: true
  assets:
    - "*.png"
    - "*.jpg"
  cache: .asset-cache

# jekyll-responsive-image
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 100
  sizes:
    - width: 20
    - width: 480
    - width: 800
    - width: 1400
    - width: 2800
  output_path_format: assets/images/%{filename}-%{width}.%{extension}
