# Site settings
title: dolm.us
header-img: img/kadikoy.jpg
description: "A site not really about dolmus"
baseurl: ""
url: "http://dolm.us"
github_username:  behcet
timezone: America/New_York

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
exclude: [
  "node_modules",
  "Gruntfile.js",
  "package.json",
  "README.md",
  "vendor",
  "Gemfile",
  "deploy.conf",
  "deploy.sh",
  "build.sh"
]

gems: [jekyll-assets, jekyll-paginate, jekyll-feed, bootstrap-sass, uglifier]
# Serve settings
host: 0.0.0.0

# App specific
social:
  - title: github
    url: https://github.com/behcet
  - title: linkedin
    url: https://www.linkedin.com/pub/behcet-uyar/4b/457/661

# jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/img
    - _assets/js
    - _assets/scss
  compress:
    js: true
    css: true
  digest: true
  cache: .asset-cache
