# Site settings
title: dolm.us
header-img: kadikoy.jpg
description: "A site not really about dolmus"
baseurl: ""
url: "http://dolm.us"
github_username:  behcet
timezone: America/New_York

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
exclude: [
  "node_modules",
  "Gruntfile.js",
  "package.json",
  "README.md",
  "Gemfile",
  "deploy.conf",
  "deploy.sh",
  "build.sh"
]

gems: [jekyll-assets, jekyll-paginate, jekyll-feed, bootstrap-sass, uglifier]
# Serve settings
host: 0.0.0.0

# App specific
social:
  - title: github
    url: https://github.com/behcet
  - title: linkedin
    url: https://www.linkedin.com/pub/behcet-uyar/4b/457/661

# jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/js
    - _assets/scss
  compress:
    js: true
    css: true
  digest: true
  assets:
    - "*.png"
    - "*.jpg"
  cache: .asset-cache

# jekyll-responsive-image
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: _assets/image

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}
